"""add_created_by_to_workflow

Revision ID: 94a8fc1e3530
Revises: 1c268fa6eff5
Create Date: 2026-02-11 00:12:14.418376

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94a8fc1e3530"
down_revision: str | None = "1c268fa6eff5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow", sa.Column("created_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_workflow_created_by_user"),
        "workflow",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_workflow_created_by_user"), "workflow", type_="foreignkey"
    )
    op.drop_column("workflow", "created_by")
    # ### end Alembic commands ###
