"""add sample_data column

Revision ID: de71cf55f6c9
Revises: a1b2c3d4e5f7
Create Date: 2026-01-25 22:33:35.779569

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de71cf55f6c9"
down_revision: str | None = "a1b2c3d4e5f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_organization_tier_organization_id", "organization_tier", type_="unique"
    )
    op.create_index(
        op.f("ix_organization_tier_organization_id"),
        "organization_tier",
        ["organization_id"],
        unique=True,
    )
    op.add_column(
        "workflow",
        sa.Column(
            "sample_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow", "sample_data")
    op.drop_index(
        op.f("ix_organization_tier_organization_id"), table_name="organization_tier"
    )
    op.create_unique_constraint(
        "uq_organization_tier_organization_id",
        "organization_tier",
        ["organization_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
